-- Mokhles Group HR Analytics starter measures

Active Headcount =
CALCULATE(
    DISTINCTCOUNT('01_dim_employee_fy2025'[employee_id]),
    '01_dim_employee_fy2025'[employment_status] = "Active at FY2025 year-end"
)

Employees Represented =
DISTINCTCOUNT('01_dim_employee_fy2025'[employee_id])

FY2025 Hires =
SUM('02_fact_monthly_hr_kpi_fy2025'[hires])

FY2025 Exits =
DISTINCTCOUNT('06_fact_employee_separations_fy2025'[employee_id])

Turnover Rate =
DIVIDE(
    [FY2025 Exits],
    AVERAGE('02_fact_monthly_hr_kpi_fy2025'[average_headcount])
)

Total Payroll Cost BDT =
SUM('02_fact_monthly_hr_kpi_fy2025'[payroll_cost_bdt])

Annual Total Reward BDT =
SUM('10_fact_compensation_benefits_fy2025'[annual_total_reward])

Average Performance Score =
AVERAGE('11_fact_performance_evaluation_fy2025'[overall_score])

Training Hours =
SUM('09_fact_training_development_fy2025'[hours])

Training Cost BDT =
SUM('09_fact_training_development_fy2025'[cost_bdt])

Approved Leave Days =
CALCULATE(
    SUM('07_fact_leave_transactions_fy2025'[leave_days]),
    '07_fact_leave_transactions_fy2025'[approval_status] = "Approved"
)

Recruitment Cost BDT =
SUM('05_fact_recruitment_fy2025'[recruitment_cost_bdt])

Average Time to Fill =
AVERAGE('05_fact_recruitment_fy2025'[time_to_fill_days])

Female Headcount =
CALCULATE(
    DISTINCTCOUNT('08_dim_diversity_inclusion_fy2025'[employee_id]),
    '08_dim_diversity_inclusion_fy2025'[gender] = "Female"
)

Female Representation =
DIVIDE(
    [Female Headcount],
    DISTINCTCOUNT('08_dim_diversity_inclusion_fy2025'[employee_id])
)

Regrettable Exits =
CALCULATE(
    DISTINCTCOUNT('06_fact_employee_separations_fy2025'[employee_id]),
    '06_fact_employee_separations_fy2025'[regrettable_exit] = "Yes"
)
